services:

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - '7080:8080'
      - '50000:50000'
    container_name: jenkins
    volumes:
      - ~/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  sonar-db:
    image: postgres:13
    container_name: sonar-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    networks:
      - sonar-net

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    depends_on:
      - sonar-db
    ports:
      - '9000:9000'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - sonar-net
    restart: unless-stopped

volumes:
  sonar-db-data:
  sonarqube_data:
  sonarqube_extensions:
  jenkins-data:
    driver: local

networks:
  sonar-net:
    driver: bridge
